### ISSUE TITLE
咨询：密码设置方式问题。

### ISSUE THREAD

**Issue by narra2024** [Lorem3/no-style-please2-plugins#1]
抱歉，我又来提问了。

“no-style-please2“的[**readme**](https://github.com/vitock/no-style-please)里说，密码要放到“_config.yml”里，并且不推荐明文形式。
“no-style-please2-plugins”的[**readme**](https://github.com/vitock/no-style-please2-plugins)里说，密码是写到“post front”里。

我想问：
1.密码是以明文方式写到“_config.yml”或“post front”里吗，本机生成网页和由github生成网页时都可以写明文的吗？
2.“no-style-please2“的readme里说，“add JEKYLL_EC_PRIVATEKEY to ENV before you run jekyll build or set JEKYLL_EC_PRIVATEKEY to your CI environment”，能不能告知，在windows上是怎么操作的。

感恩您在[上一个咨询](https://github.com/vitock/no-style-please/issues/1)里和这里的解答。

**Comment by Lorem3** [comment]
1. 是的，都可以直接明文
2. 如果你想加密密码，就是按照readme， 通过ltectool 生成公钥对，加密你想加密的密码，windows 环境变量的设置，可以去搜索一下，windows下，我还没执行过 🤷

> 如果你按照 Jekyll步骤安装了依赖，ltectool应该就已经安装了

**Comment by narra2024** [comment]
好的，太感谢您的热心回答了。祝您一切好运！

**Comment by narra2024** [comment]
请问我需要生成一对公匙和私匙，写到“_config.yml”或其它文件里吗？

**Comment by Lorem3** [comment]
> 请问我需要生成一对公匙和私匙，写到“_config.yml”或其它文件里吗？

需要公钥私钥，但不用写在config里面，config.yml只存加密的密码，私钥配置在ci的环境变量里面就行了

**Comment by narra2024** [comment]
但您的“actions”“build”里，也写着“[JEKYLL_EC_PRIVATEKEY is not set](https://github.com/vitock/no-style-please/actions/runs/12525038640/job/34936192974)”，但也可以加密，说明用github的时候，不需要设置私匙是吗？

**Comment by narra2024** [comment]
早点儿休息，晚安！

**Comment by Lorem3** [comment]
> 但您的“actions”“build”里，也写着“[JEKYLL_EC_PRIVATEKEY is not set](https://github.com/vitock/no-style-please/actions/runs/12525038640/job/34936192974)”，但也可以加密，说明用github的时候，不需要设置私匙是吗？

没设置会设置一个默认的，用于这个demo运行

**Comment by Lorem3** [comment]
@narra2024 写了个web工具
这里可以生成密码，加密密码，
https://vitock.github.io/jekyll-zeta/post/2024/12/30/ToolForEncryption.html
